/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.thread;

import 
        java.io.IOException;
ion; import;
java.nio.charset.Charset;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.list;

public class singgle{
    public void proses() throws IOException
    {List <Hasil pencarian> listHasil = new ArrayList<>();
    }
List <String>ListBaris = Files.readAlllines(
        paths.get("C:\\data.txt"),
        Charset.defaultCharset());
}


